### ISSUE TITLE
3.5.0:  The colors of local and origin branches are reversed (Red/Green)

### ISSUE THREAD

**Issue by MatthieuHernandez** [gitextensions/gitextensions#9189]
### Before (version 3.4.3.9999):
![image](https://user-images.githubusercontent.com/25429726/117644904-466bb880-b18a-11eb-9974-ffbdf37383cf.png)

### After (version 3.5.0.11713):
![image](https://user-images.githubusercontent.com/25429726/117645156-8df24480-b18a-11eb-8ee2-9c268c159e38.png)

Same with light theme.

I don't know if it's a bug or a feature but I didn't see anything about it in the Changelog.

**Comment by pmiossec** [comment]
Done in purpose (even if not every one agree on that). Already discussed in details in #9113
Could be reverted by the user creating a custom theme.
So closing...

**Comment by MatthieuHernandez** [comment]
Thanks

**Comment by wdspider** [comment]
FWIW: In case others like me stumble on this thread trying to figure out what went wrong.  I ended up simply switching the class names on line 41 and line 43 in the existing dark.css file to revert this change:
![image](https://user-images.githubusercontent.com/5971649/118680426-944c7600-b7b3-11eb-9f1b-9df78b88b525.png)

**Comment by pmiossec** [comment]
> FWIW: In case others like me stumble on this thread trying to figure out what went wrong. I ended up simply switching the class names on line 41 and line 43 in the existing dark.css file to revert this change:

A better solution would be to create a custom theme in your user folder:
![image](https://user-images.githubusercontent.com/460196/118682472-c506cc80-b800-11eb-912b-4fe63253784f.png)

based on the original theme but with only the 2 colors inverted like:

```css
@import url("dark.css");
.Branch                      { color: #ff8080; }
.RemoteBranch                { color: #00d76b; }
````

or

```css
@import url("bright.css");
.Branch                  { color: #e66363; }
.RemoteBranch            { color: #22a639; }
```

That way it won't be lost in an application update...
